# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aZbCDo9p6byqDL--O94b04zcGfMbwiU2
"""

import base64
import json
import boto3
import time

# Initialize the S3 client
s3 = boto3.client('s3')
bucket_name = 'ecommerce-data-platform'
s3_key_prefix = 'raw/transactions/'

def lambda_handler(event, context):
    for record in event['Records']:
        # Kinesis data is base64 encoded
        payload = base64.b64decode(record['kinesis']['data']).decode('utf-8')
        # Generate a unique key for the S3 object
        timestamp = int(time.time())
        s3_key = f"{s3_key_prefix}{timestamp}.json"
        # Save the payload to S3
        s3.put_object(Bucket=bucket_name, Key=s3_key, Body=payload)
        print(f"Saved record to {s3_key}")
    return 'Success'