# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/174PPOIRgtLplCI1BBi8ViJ3DBsomXpgz
"""

!pip install boto3

import boto3
import csv
import json
import time


# AWS credentials and region
aws_access_key_id = 'AKIAU6GDXVZUJWW3ELMF'
aws_secret_access_key = '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'
region_name = 'us-east-1'

# Create a Kinesis client
kinesis_client = boto3.client(
    'kinesis',
    aws_access_key_id=aws_access_key_id,
    aws_secret_access_key=aws_secret_access_key,
    region_name=region_name
)

# Kinesis Data Stream name
stream_name = 'Store'

# Load the dataset
with open('online_retail.csv', 'r') as file:
    reader = csv.DictReader(file)
    for row in reader:
        # Convert each row to JSON format
        data = json.dumps(row)
        # Send the data to Kinesis Data Stream
        response = kinesis_client.put_record(
            StreamName=stream_name,
            Data=data,
            PartitionKey=row['CustomerID'] if row['CustomerID'] else 'default'
        )
        print(f"Put record: {response}")
        # Sleep to simulate real-time data streaming
        time.sleep(1)  # Adjust the sleep time as needed

print("Finished sending data to Kinesis Data Stream.")

